### ISSUE TITLE
Hymns and Gospels

### ISSUE THREAD

**Issue by Sarto1** [DivinumOfficium/divinum-officium#1139]
Hello,

Two suggestions I want to make:

1. In the hymns, would it be possible to write the letters in cursive which are omitted? For example "Et Filio qu_i_ a mortuis", so it's easier to see which ones are sung, and which ones aren't?

2. It would also be really helpful if the Gospels for Matins were written out completely, so I don't have to look them up elsewhere which is also quite impossible when I'm using the site on the train, and don't have access to a printed Breviary according to the pre Pius X use.

Thank you very much!

**Comment by APMarcello3** [comment]
1) At some point in the future, it may be possible to provide the chant notation for the hymns. However, since the main goal of this site is intended to re-present what is found in the Breviarium Romanum, such orthography is not found as such in the Breviarium.

2) The Gospels at Matins were not read in full. They were always ended with "Et reliqua."
