### ISSUE TITLE
Croatian "translation" is a copy of the Latin files

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#1150]
35b447a adds a Croatian translation consisting in a slightly outdated copy of the Latin files. This commit should be reversed (i.e., all the files should be deleted), preferably by @Griffinovski, who made the commit.

What we should learn from this is that we need a guide for new collaborators who want to produce a translation. Here are my suggestions for what it should say:

1. You do not need to copy the files for another language (Latin, English, …) and should not do so. Where there is not a translation in the selected language, the program falls back to the English translation, or to the Latin if there is no English.
2. This fallback process works section by section, so you can translate just part of a file, omitting the sections not yet translated.
3. If a section of the Latin file only contains a reference, do not provide a translation for that section. Instead, place the translation in the referenced file. This avoids the duplication of texts, and means that errors can be corrected in just one place instead of two or more.
4. Make sure you have the right to use the translation you choose, whether it is a complete translation of the breviary or a translation of the Bible.
5. (My opinion) If you use a Bible, choose a translation of the Latin Vulgate so that it corresponds to the Psalms (the Gallican psalter, which is a translation of the Septuagint). Most of the texts in the Breviary are biblical, and can be copied from or based on the corresponding texts in a translation of the Vulgate.
6. (My opinion again) Start with commonly used texts: the Psalms (especially the Sunday Psalms), the Ordinary, the Commons. 

I suggest placing a guide like this in the Wiki.

**Comment by Griffinovski** [comment]
Dear @fiapps. Hello, first I am a priest not a programmer so forgive me the lack of my technical and programming knowledge. I am familiarizing with everything. I have some basic knowledge but this is new to me.
Considering your points:
Reply to 1: In the e-mail, fr. Marcello indicated me the following: "_The Latin files (web/www/horas/Latin) are in *.txt format and must also remain in UTF-8 encoding. Once cloning the repository, it is recommended to copy the files found in the Latin folders and use them to create a new Croatian folder. Once there, the Latin texts may be overwritten with Croatian._ " Also,  I know that the program fills the english in the untranslated parts.
Considering 4,5,6: This is clear to me. As the full Breviary was never fully translated in Croatian, I will use the collection of partial translations which are already public domain. On the other part, I will use an old translation of the psalter which was done in 1932 because all the newer were done according to the hebrew text. Some corrections will be done to update the language or to adjust the latin translation in croatian. In the end, all the parts which were not translated fully like the readings will be translated from vernacular or latin to fill the missing parts. As we know, Summorum Pontificum allows only the breviary to be prayed in latin, so the vernacular part is just a help to understand the latin. The steps are the following: Ordinary, Psalter (starting by Sunday) and Commons and Matins as last. 

In the end, should I erase all the latin text files and fill them paritally as they are prepared or I should I leave them and edit them as fr. Marcello asked?

P.S. A guide for the collaborators would be a good idea.

**Comment by APMarcello3** [comment]
A wiki for modern languages has been added: https://github.com/DivinumOfficium/divinum-officium/wiki/New-Languages

**Comment by fiapps** [comment]
@Griffinovski, I didn't realize Fr. Marcello had told you to do that. I thought I was simply describing the best practice established over the last several years. In the event of any conflict between us, you should do what he says, since he administers this repository, and I only contribute to it. Don't erase the Latin files unless he tells you to do so.

**Comment by mbab** [comment]
> A wiki for modern languages has been added: https://github.com/DivinumOfficium/divinum-officium/wiki/New-Languages

Correct link is https://github.com/DivinumOfficium/divinum-officium/wiki/Modern-Languages
