### ISSUE TITLE
Commemoration of Sunday infra Oct Nat is missing

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#1315]
Trient 1910: there should be a commemoration of the Sunday infra Octavam Nativitatis on 30 Dec 2019, feast of St Thomas, with lectio IX.

Also the psalms at vespers on the same day are wrongly taken from the common of martyrs instead of from the Nativity.

**Comment by gregordick** [comment]
I've fixed the missing commemoration in 2521dba.  The [psalmody at Vespers](https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-29-2019&command=prayVespera&version=Tridentine%201910&testmode=regular&lang2=English&votive=) already appears to be of the octave.  There's been no obvious change there, since the datafile reference that achieves this has been there since 2016.

**Comment by gregordick** [comment]
The ninth lesson at Matins is still wrong, but that's an independent bug and one that I'm disinclined to worry about for now.  I'll split it out into a new issue.
