### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Sarto2** [DivinumOfficium/divinum-officium#1999]
A while ago, I offered to help with the German translation of the Divine Office. Unfortunately, nothing has come of it yet. Please be so kind to incorporate the following improved texts into the files (if I knew how to do that, I'd do it myself, but I'm illiterate when it comes to technical stuff).

**Domine labia mea**
V Herr, öffne meine Lippen.
R Damit mein Mund dein Lob verkünde.

**Deus in adjutorium**
V O Gott, komm mir zu Hilfe.
R Herr, eile, mir zu helfen.

**Gloria Patri**
V Ehre sei dem Vater und dem Sohne und dem Heiligen Geist.
R Wie im Anfang, so auch jetzt und alle Zeit und in Ewigkeit. Amen. Halleluja.

**Jube domne/Domine benedicere**

Gib, Herr, den Segen.

**Tu autem Domine miserere nobis**

Du aber, Herr, erbarme dich unser.

**Deo gratias.**

Dank sei Gott.

**Te Deum**

Dich, Gott, loben wir, dich, Herr, preisen wir.
Dir, dem ewigen Vater, huldigt das Erdenrund.
Dir rufen die Engel alle,
dir Himmel und Mächte insgesamt,
die Kerubim dir und die Serafim,
mit niemals endender Stimme zu:
Heilig, heilig, heilig
der Herr, der Gott der Scharen!
Voll sind Himmel und Erde
von deiner hohen Herrlichkeit.

Dich preist der glorreiche Chor der Apostel;
dich der Propheten lobwürdige Zahl;
dich der Märtyrer leuchtendes Heer;
dich preist über das Erdenrund die heilige Kirche;
dich, den Vater unermessbarer Majestät;
deinen wahren und einzigen Sohn;
und den Heiligen Fürsprecher Geist.

Du König der Herrlichkeit, Christus.
Du bist des Vaters allewiger Sohn.
Du hast der Jungfrau Schoß nicht verschmäht, bist Mensch geworden, den Menschen zu befreien.
Du hast bezwungen des Todes Stachel und denen, die glauben, die Reiche der Himmel aufgetan.

Du sitzest zur Rechten Gottes in deines Vaters Herrlichkeit.
Als Richter, so glauben wir, kehrst du einst wieder.
Dich bitten wir denn, komm deinen Dienern zu Hilfe, die du erlöst mit kostbarem Blut.
In der ewigen Herrlichkeit zähle uns deinen Heiligen zu.

Rette dein Volk, o Herr, und segne dein Erbe;
und führe sie und erhebe sie bis in Ewigkeit.
An jedem Tag benedeien wir dich
und loben in Ewigkeit deinen Namen, ja, in der ewigen Ewigkeit.
In Gnaden wollest du, Herr, an diesem Tag uns ohne Schuld bewahren.

Erbarme dich unser, o Herr, erbarme dich unser.
Lass über uns dein Erbarmen geschehn, wie wir gehofft auf dich.
Auf dich, o Herr, habe ich meine Hoffnung gesetzt. In Ewigkeit werde ich nicht zuschanden.

**Domine exaudi**

V Herr, erhöre mein Gebet.
R Und lass mein Rufen zu dir kommen.

**Benedicamus Domino**

V Singet Lob und Preis.
R Dank sei Gott, dem Herrn.

**Fidelium animae**

Die Seelen der Gläubigen mögen durch die Barmherzigkeit Gottes ruhen in Frieden.

**Dominus vobiscum**

V Der Herr sei mit euch.
R Und mit deinem Geiste.

**Confiteor**

Ich bekenne Gott, dem Allmächtigen, der seligen, allzeit reinen Jungfrau Maria, dem heiligen Erzengel Michael, dem heiligen Johannes dem Täufer, den heiligen Aposteln Petrus und Paulus und allen Heiligen (priest: allen Heiligen und euch, Brüder,)(lay/acolythe: allen Heiligen und dir, Vater,), dass ich viel gesündigt habe in Gedanken, Worten und Werken: durch meine Schuld, durch meine Schuld, durch meine große Schuld.
Darum bitte ich die selige, allzeit reine Jungfrau Maria, den heiligen Erzengel Michael, den heiligen Johannes den Täufer, die heiligen Apostel Petrus und Paulus und alle Heiligen (priest: alle Heiligen und euch, Brürder,)(lay/acolythe: alle Heiligen und dich, Vater,) für mich zu beten bei Gott, unserem Herrn.

**Misereatur**

(singular)
Der allmächtige Gott erbarme sich unser, er lasse uns die Sünden nach und führe uns zum ewigen Leben. Amen.
(faithful to priest)
Der allmächtige Gott erbarme sich deiner, er lasse dir die Sünden nach und führe dich zum ewigen Leben. Amen.
(priest to faithful)
Der allmächtige Gott erbarme sich euer, er lasse euch die Sünden nach und führe euch zum ewigen Leben. Amen.

**Indulgentiam**

Nachlass, Vergebung und Verzeihung unserer Sünden gewähre uns der allmächtige und barmherzige Gott. Amen.

**Converte nos**

V Bekehre uns, Gott, unser Heil.
R Und wende Deinen Zorn von uns ab.

**In manus tuas**

R br In deine Hände, Herr, empfehle ich meinen Geist.
R In deine Hände, Herr, empfehle ich meinen Geist.
V Du hast uns erlöst, Herr, Gott der Wahrheit.
R Empfehle ich meinen Geist.
V Ehre sei dem Vater und dem Sohne und dem Heiligen Geist.
R In deine Hände, Herr, empfehle ich meinen Geist.

**Salva nos**

Sei unser Heil, o Herr, wenn wir wachen, und unser Schutz, wenn wir schlafen; damit wir wachen mit Christus und ruhen in seinem Frieden.

**Oratio: Visita quaesumus**

Herr und Gott, kehre ein in dieses Haus und halte alle Nachstellungen des Feindes von ihm fern. Deine heiligen Engel mögen darin wohnen und uns im Frieden bewahren. Und dein Segen sei über uns allezeit. Durch unseren Herrn Jesus Christus, deinen Sohn, der mit dir lebt und herrscht in der Einheit des Heiligen Geistes, Gott, von Ewigkeit zu Ewigkeit. Amen.

**Conclusiones longiores**

_Per Dominum_
Durch unseren Herrn Jesus Christus, deinen Sohn, der mit dir lebt und herrscht in der Einheit des Heiligen Geistes, Gott, von Ewigkeit zu Ewigkeit.

_Qui tecum_
Der mit dir lebt und herrscht in der Einheit des Heiligen Geistes, Gott, von Ewigkeit zu Ewigkeit. Amen.

_Qui vivis_
Der du lebst und herrschst mit Gott, dem Vater, in der Einheit des Heiligen Geis-tes, Gott, von Ewigkeit zu Ewigkeit. Amen.

**Conclusiones breviores**

_Per Christum_
Durch Christus, unseren Herrn. Amen.

_Qui vivit_
Der lebt und herrscht von Ewigkeit zu Ewigkeit. Amen.

_Qui vivis_
Der du lebst und herrschst von Ewigkeit zu Ewigkeit. Amen.

**Canticum Benedictus**

Gepriesen sei der Herr, der Gott Israels! Denn er hat sein Volk besucht und ihm Erlösung geschaffen;
er hat uns einen starken Retter erweckt im Hause seines Knechtes David.
So hat er verheißen von alters her durch den Mund seiner heiligen Propheten.
Er hat uns errettet vor unseren Feinden und aus der Hand aller, die uns hassen;
er hat das Erbarmen mit den Vätern an uns vollendet und an seinen heiligen Bund gedacht,
an den Eid, den er unserm Vater Abraham geschworen hat;
er hat uns geschenkt, dass wir, aus Feindeshand befreit, ihm furchtlos dienen
in Heiligkeit und Gerechtigkeit vor seinem Angesicht all unsre Tage.
Und du, Kind, wirst Prophet des Höchsten heißen; denn du wirst dem Herrn vorangehen und ihm den Weg bereiten.
Du wirst sein Volk mit der Erfahrung des Heils beschenken in der Vergebung seiner Sünden.
Durch die barmherzige Liebe unseres Gottes wird uns besuchen das aufstrahlende Licht aus der Höhe,
um allen zu leuchten, die in Finsternis sitzen und im Schatten des Todes, und unsre Schritte zu lenken auf den Weg des Friedens.

**Canticum Magnificat**

Meine Seele preist die Größe des Herrn
und mein Geist jubelt über Gott, meinen Retter.
Denn auf die Niedrigkeit seiner Magd hat er geschaut. Siehe, von nun an preisen mich selig alle Geschlechter.
Denn der Mächtige hat Großes an mir getan und sein Name ist heilig.
Er erbarmt sich von Geschlecht zu Geschlecht über alle, die ihn fürchten.
Er vollbringt mit seinem Arm machtvolle Taten: Er zerstreut, die im Herzen voll Hochmut sind;
er stürzt die Mächtigen vom Thron und erhöht die Niedrigen.
Die Hungernden beschenkt er mit seinen Gaben und lässt die Reichen leer ausgehen.
Er nimmt sich seines Knechtes Israel an und denkt an sein Erbarmen,
das er unsern Vätern verheißen hat, Abraham und seinen Nachkommen auf ewig.

**Canticum Nunc dimittis**

Nun lässt du, Herr, deinen Knecht, wie du gesagt hast, in Frieden scheiden.
Denn meine Augen haben das Heil gesehen,
das du vor allen Völkern bereitet hast,
ein Licht, das die Heiden erleuchtet, und Herrlichkeit für dein Volk Israel.

**Divinum auxilium**

V Die göttliche Hilfe bleibe allezeit bei uns.
R Amen.

Those are official liturgical texts, prepared by the German Bishops' Conference (DBK). I have no clue where the current texts have been taken from, but they are almost gruesome.

If desired, I can also provide the texts for the psalms, canticles, lessons, readings etc. from official liturgical sources or translations approved by the Holy See and the DBK.

**Comment by APMarcello3** [comment]
Closed by 3c92cc2.

**Comment by fiapps** [comment]
These are my personal opinions as a non-native speaker. It would be interesting to hear from more German users about the translation they prefer. In English, some like an old-fashioned translation because it distinguishes sacred texts from ordinary speech, while others prefer a modern translation that is easier to understand—non-natives using the English translation are overwhelmingly in the latter category.

Official liturgical texts are not, in general, the most suitable for the purposes of this project, because they were usually produced with a preference for something that would read well in the receptor language rather than something that would accurately convey the meaning of the Latin. The translations for this project, on the other hand, are not meant to be prayed on their own, but to serve as an aid to understanding the Latin. However, the German liturgical translations struck me when I first saw them as unusually faithful to the original Latin, in comparison to the English and Italian translations. So I would say that they are the exception where an official liturgical translation would be suitable. It may be that some phrases are problematic, because the German bishops proved highly allergic to _Liturgiam authenticam,_ so there must have been some things that they didn't want to translate accurately, but I think that's the exception.

On the other hand, insofar as the Hebrew differs from the Latin, I don't think the official translations of psalms, canticles, lessons, readings etc. would be generally suitable as an aid to understanding the Latin.

**Comment by Sarto2** [comment]
German translations have been around for nearly 100 years, and they haven't changed much. What I have given above as the authentic translation, is attested to in most historical books as well. Surprisingly, the current official texts are quite traditional in this regard. Translating "Benedicamus Domino" with "Singet Lob/Preis und Dank" is a poetic translation, not a literal one.

Also, I'm using the historical books as a source (prepared e. g. by the Benedictine monks of Beuron), which were published during the Golden Age of the Liturgical Movement, and they produce a brillant synthesis between literal and poetic translations.

What is featured right now as the German translation is crude, the translations are cretinous. It's not that they are in an "old timey" German, they are simply done pretty badly.

When it comes to the German translation of psalms etc. I would use the Allioli-Arndt translation of Holy Scripture, which faithfully transmits the Latin Vulgate, and has been approved by the Popes (it used to be the official German translation before the Einheitsübersetzung after Vatican II). It's a noble translation, and the translator clearly had in mind that the psalms would be prayed, so they aren't too literal/technical.

**Comment by peterdiekertz** [comment]
I must disagree, partially. As the credit page clearly says, the German translations are mostly from "Das kirchliche Stundengebet oder Das römische Brevier. Übersetzt und erklärt von Erzpriester Stephan" (Pustet 1926). Some texts however are also changed to a well-known form (like the Ave Maria).

As @fiapps says, they're very literal. I chose that version because that is what I had available - and still have - when I started and because I specifically did not want to take the modern Einheitsübersetzung - not least because of copyright reasons. I don't believe it would be permissible to do that. Neither can we take Ramm FSSP's translation of course, for the same reason (I was in contact with him and understandably they don't want to put it in the public domain).

So I wouldn't mind changing some versicles to common forms of today. But the Stephan translation still is a traditional version and I do not mind it. For example, "O Gott komm mir zu Hilfe" is but one possibility of translating "Deus in adiutorium". In old prayer books, I have seen countless variants, not just that one. 

And aren't the texts of the Te Deum, Benedictus, Magnificat, Nunc dimittis etc. which you propose all from the Stundenbuch [Liturgia Horarum in the vernacular] and so also from the (old) Einheitsübersetzung? They don't strike me as very traditional then. Take only the problem in the Benedictus described at https://katholisch-ohne-furcht-und-tadel.de/2020/07/15/die-erkenntnis-des-heils-unnoetige-uebersetzungspannen/

**Comment by fiapps** [comment]
I'll just add that if there are—or we think there are—users who appreciate more than one German translation, there's already a mechanism to support partial replacement of a translation. It's used in Polish to offer a more recent translation of the Psalms (used with permission).
