### ISSUE TITLE
Tridentine anticipated Sundays

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DivinumOfficium/divinum-officium#220]
From a correspondent:

In both cases the anticipated Sunday is seriously wrong on the site.

Prior to 1911-13 anticipated Sundays are of simple rite, not semidouble.  They do not have first Vespers.  Mattins is the single ferial nocturn of twelve psalms (and Ps. 91 does not replace Ps. 99).  The lessons are the homily of the Sunday.  At Mass there is no Creed.

If a feast of nine lessons falls on the Saturday and there is a ferial day, or a feast of three lessons in the preceding week, then the Sunday is anticipated on that day, not the Saturday.  When there is no such day then in the festal Office on Saturday the Scriptural lessons are those of the Sunday and the Sunday’s homily is read as the ninth lesson.

Original issue reported on code.google.com by `igregord` on 15 Feb 2014 at 2:00

**Comment by peterdiekertz** [comment]
The problem with Ps. 91 was solved in #551.
There is a general problem with displaying the ferial psalter on "Tridentine" Saturdays: #556

**Comment by APMarcello3** [comment]
From fiapps, regarding the 01-30-2021 Tridentine office (anticipated Sunday):

Something is wrong with Saturday matins when the Trent rubrics are used. The sixth psalm is the last one shown, and it is followed by this instead of the text of the remaining psalms:

Bénedic * ánima mea Dómino;;103;104
Vísita nos * Dómine in salutári tuo;;105;106

Something similar happens in the English column:

Bless the Lord * O my soul.;;103;104
Visit us * with Thy salvation, O Lord.;;105;106
