### ISSUE TITLE
Liturgical color for Holy Monday through Spy Wednesday is now black

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#2555]
The refactoring of the code to select the liturgical color into `DivinumOfficium::Main` has had the side effect of changing the liturgical color from purple to black for Feria Secunda Hebdomadæ Sanctæ through Feria Quarta Hebdomadæ Sanctæ. It's odd, because the new code does seem to be testing for "Hebdomadæ Sanctæ".

My testing uses 2018 (3-26-2018 – 3-28-2018), but this is also reproducible in 2021:
https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-29-2021&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=Latin&votive=
https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-30-2021&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=Latin&votive=
https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-31-2021&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=Latin&votive=

**Comment by ajmalton** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} The Main module should use utf8 since now it has non ASCII characters in it .The match fails because æ has multiple representations.AJM                                                                                                                                                                                                                                                                                                                        From: ***@***.***Sent: 9 July 2021 04:05To: ***@***.***Reply to: ***@***.***Cc: ***@***.***Subject: [DivinumOfficium/divinum-officium] Liturgical color for Holy Monday through Spy Wednesday is now black (#2555)  

The refactoring of the code to select the liturgical color into DivinumOfficium::Main has had the side effect of changing the liturgical color from purple to black for Feria Secunda Hebdomadæ Sanctæ through Feria Quarta Hebdomadæ Sanctæ. It's odd, because the new code does seem to be testing for "Hebdomadæ Sanctæ".

My testing uses 2018 (3-26-2018 – 3-28-2018), but this is also reproducible in 2021:

https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-29-2021&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=Latin&votive=

https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-30-2021&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=Latin&votive=

https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-31-2021&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=Latin&votive=



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by APMarcello3** [comment]
@mbab Would you kindly fix?
