### ISSUE TITLE
The page isn't more responsive

### ISSUE THREAD

**Issue by thadeusoares** [DivinumOfficium/divinum-officium#2642]
I got that an update in divinumofficium.com made the page without responsiveness on my devices (iPhone and iPad).
On Android looks great.

Follow some samples that are bad to read

![photo_2021-10-14_10-54-22](https://user-images.githubusercontent.com/1102686/137331595-1aa35a7d-abfe-41a1-a948-c8987095ada1.jpg)
![photo_2021-10-14_10-54-19](https://user-images.githubusercontent.com/1102686/137331608-aae72ba7-01a1-4ab6-9029-a109834ad9d2.jpg)

**Comment by ajmalton** [comment]
I cannot see the problem, apart from the fact that the Portuguese translation is incomplete.

They loaded rapidly for me on my device.

Can you say more specifically what the problem is?

**Comment by ajmalton** [comment]
They certainly are different.  However, the Options are currently managed separately for mobile officium, desktop officium, and missa.  (Probably this shouldn't be so.) And also there is no user session on the server so the Options are stored locally on each client device, and may well be different.

A few months ago there was a correction to Options handling for missa.  

May I ask you to compare the same Office or Mass on both devices? And also to touch the Options link and make sure that the font size etc is exactly the same in the two devices?

**Comment by ajmalton** [comment]
So, although I’m not certain, I think I've seen this before and it seems to be related to WebCore’s handling of our (obsolete) font size specifications. Chrome is at least sometimes responsive to the device size or window size, in ways we do not directly control.

In other words it's possible that the difference is caused by the browser itself, rendering the _same_ HTML on different devices.  That would be more certainly true if your Options really are exactly the same on both devices: for then the HTML is really byte for byte the same.

The solution is to move to modern responsive methods with CSS that adjusts the look and feel more correctly. That will eventually be done, but unfortunately not soon.

In the meantime, do try adjusting your Options on each device you use, to get the best look and size you can.
