### ISSUE TITLE
Lavabo during Requiem

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#278]
During a Requiem Mass, the Lavabo shouldn't be concluded with a Requiem aeternam etc. See for example, p. 303, of the pdf of the 1962 Missale Romanum

http://media.musicasacra.com/pdf/missale62.pdf

**Comment by petermottola** [comment]
This issue seems to have been fixed, but should probably be left open because there are several related issues regarding Masses for the Dead.  For example the following rubric is included at the Gospel but is inaccurate:
"Et pronuntians: Inítium, sive Sequéntia sancti Evangélii, signat librum, et se in fronte, ore et pectore, et legit Evangelium, ut dictum est. Quo finito, respondet Minister: Laus tibi, Christe, et Sacerdos osculatur Evangelium, dicens: per evangelica dicta, ut supra."  The priest, however, does not kiss the book, as is said on page 219 [PDF 300] of the resource linked in OP: "In Missis defunctorum dicitur Munda cor meum, sed non petitur benedictio, non deferuntur luminaria, nee celebrans osculatur librum."
Another example of a rubric taken from non-requiem Masses in error, e.g.:
"Deinde faciens crucem cum eadem Patena, deponit Hostiam super Corporale. Diaconus ministrat vinum, Subdiaconus aquam in Calice: vel si privata est Missa, utrumque infundit Sacerdos, et aquam miscendam in Calice benedicit signo crucis, dicens:" etc.  But the priest does not make the sign of the cross over the water: "In Missis defunctorum dicitur praedicta oratio: sed aqua non benedicitur." [p. 221 / PDF 302]

**Comment by APMarcello3** [comment]
Closed by 1794fe8f6.

**Comment by APMarcello3** [comment]
Workaround made in 61a2f0589.
