### ISSUE TITLE
Martyrology updates (1962)

### ISSUE THREAD

**Issue by rarty** [DivinumOfficium/divinum-officium#280]
This is a great tool, and it includes probably the most complete/updated Martyrology available outside of a rare-books shop. 

I have a substantial update I'd like to make to the Latin Martyrology texts that would add accute accent marks and the common vowel ligatures. I checked against the latest Roman edition (ed. IV, 1956), and incorporated the changes from the 1961 "Variationes in Mart. Rom." As I'm not sure which editions the older historical versions of the office do/should use, I can't do much yet for those.

A few things I'd like other opinions on before I make a PR:

1. It looks like the "rubrics 1960" office currently uses the texts in the `Martyrologium2` folder, but since "reduced 1955" does too, I think that 1960 version should be distinct, i.e, `Martyrologium3`, and 1960-only changes removed from `Martyrologium2`.

2. Should the consonant `j` be retained *in toto,* or only for foreign/non-Latin names? (As in the modern Martyrology)

3. Can all the files be encoded UTF-8?

4. I can't find a rubric that prescribes the announcing of the year along with the moon each day, eg. "Anno Domini 2015" in the 1961 Breviary or in the 1956 Martyrology. Is this a received usage/monastic tradition?

Thanks,

KTL

**Comment by ajmalton** [comment]
1 I agree, although if the differences are very few, I wonder if Laszlo had a good reason not to use just one set. How large is the difference?2 Unless the logic has been changed in the divinum code, then the rule is that j is replaced with i everywhere, starting with 1955. I don't think there's a way to retain J at all in the more modern rubrics settings (but I could be wrong, please someone correct me)3 ‎divinum data files can be in utf8 or latin1, with utf8 preferred. We really should switch them all to utf8 and get rid of the latin1 support, but work...4 it might be a Laszlo ‎Kiss tradition, like the usage of crosses etc which is a little quirkyAJM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: K. T. LartigueSent: Monday, July 6, 2015 7:04 PMTo: DivinumOfficium/divinum-officiumReply To: DivinumOfficium/divinum-officiumSubject: [divinum-officium] Martyrology updates (1962) (#280)This is a great tool, and it includes probably the most complete/updated Martyrology available outside of a rare-books shop. 

I have a substantial update I'd like to make to the Latin Martyrology texts that would add accute accent marks and the common vowel ligatures. I checked against the latest Roman edition (ed. IV, 1956), and incorporated the changes from the 1961 "Variationes in Mart. Rom." As I'm not sure which editions the older historical versions of the office do/should use, I can't do much yet for those.

A few things I'd like other opinions on before I make a PR:


It looks like the "rubrics 1960" office currently uses the texts in the Martyrologium2 folder, but since "reduced 1955" does too, I think that 1960 version should be distinct, i.e, Martyrologium3, and 1960-only changes removed from Martyrologium2.
Should the consonant j be retained in toto, or only for foreign/non-Latin names? (As in the modern Martyrology)
Can all the files be encoded UTF-8?
I can't find a rubric that prescribes the announcing of the year along with the moon each day, eg. "Anno Domini 2015" in the 1961 Breviary or in the 1956 Martyrology. Is this a received usage/monastic tradition?


Thanks,

KTL

—Reply to this email directly or view it on GitHub.

**Comment by gregordick** [comment]
On 06/07/15 23:04, K. T. Lartigue wrote:
> I have a substantial update I'd like to make to the Latin Martyrology
> texts that would add accute accent marks and the common vowel ligatures.

Thank you very much: this would be a most welcome improvement.

> I checked against the latest Roman edition (ed. IV, 1956), and
> incorporated the changes from the 1961 "Variationes in Mart. Rom." As
> I'm not sure which editions the older historical versions of the office
> do/should use, I can't do much yet for those.

The sources are listed at [1]. For orthographical changes I would not be
too concerned about following any particular edition: internal
consistency would be sufficient.

>     It looks like the "rubrics 1960" office currently uses the texts in
>     the |Martyrologium2| folder, but since "reduced 1955" does too, I
>     think that 1960 version should be distinct, i.e, |Martyrologium3|,
>     and 1960-only changes removed from |Martyrologium2|.

How extensive are the differences? The principal desired property of
such a mechanism is the avoidance of duplication of texts. It would be
straightforward to add a Martyrologium1960 directory which would
override Martyrologium2 (a) for 1960-ish rubrics only and (b) only when
the appropriate file exists in the former directory. This would fine if
the 1960-specific files were mostly completely different from their
earlier counterparts, but if the files differ only a little I would
prefer to implement support for inline conditionals as in [2].

>     Should the consonant |j| be retained /in toto,/ or only for
>     foreign/non-Latin names? (As in the modern Martyrology)

In toto, please. They will be converted to 'i' automatically (and
indiscriminately) when recent rubrics are in effect. Currently, as
Andrew suspected, there's no way to force retention of 'j'.

>     I can't find a rubric that prescribes the announcing of the year
>     along with the moon each day, eg. "Anno Domini 2015" in the 1961
>     Breviary or in the 1956 Martyrology. Is this a received
>     usage/monastic tradition?

I'm afraid I don't know -- sorry!

With thanks,
Gregor Dick


[1] http://divinumofficium.com/www/horas/Help/credits.html
[2]
https://github.com/DivinumOfficium/divinum-officium/blob/master/web/www/horas/Latin/Tempora/Epi1-0.txt

**Comment by ajmalton** [comment]
But we could easily do it with a coding trick, say jj => j and j => iI agree with conditionals too and your explanation is good.Gosh, I wish I had more time for this!AJM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Gregor DickSent: Tuesday, July 7, 2015 7:24 PMTo: DivinumOfficium/divinum-officiumReply To: DivinumOfficium/divinum-officiumCc: ajmaltonSubject: Re: [divinum-officium] Martyrology updates (1962) (#280)On 06/07/15 23:04, K. T. Lartigue wrote:
> I have a substantial update I'd like to make to the Latin Martyrology
> texts that would add accute accent marks and the common vowel ligatures.

Thank you very much: this would be a most welcome improvement.

> I checked against the latest Roman edition (ed. IV, 1956), and
> incorporated the changes from the 1961 "Variationes in Mart. Rom." As
> I'm not sure which editions the older historical versions of the office
> do/should use, I can't do much yet for those.

The sources are listed at [1]. For orthographical changes I would not be
too concerned about following any particular edition: internal
consistency would be sufficient.

>     It looks like the "rubrics 1960" office currently uses the texts in
>     the |Martyrologium2| folder, but since "reduced 1955" does too, I
>     think that 1960 version should be distinct, i.e, |Martyrologium3|,
>     and 1960-only changes removed from |Martyrologium2|.

How extensive are the differences? The principal desired property of
such a mechanism is the avoidance of duplication of texts. It would be
straightforward to add a Martyrologium1960 directory which would
override Martyrologium2 (a) for 1960-ish rubrics only and (b) only when
the appropriate file exists in the former directory. This would fine if
the 1960-specific files were mostly completely different from their
earlier counterparts, but if the files differ only a little I would
prefer to implement support for inline conditionals as in [2].

>     Should the consonant |j| be retained /in toto,/ or only for
>     foreign/non-Latin names? (As in the modern Martyrology)

In toto, please. They will be converted to 'i' automatically (and
indiscriminately) when recent rubrics are in effect. Currently, as
Andrew suspected, there's no way to force retention of 'j'.

>     I can't find a rubric that prescribes the announcing of the year
>     along with the moon each day, eg. "Anno Domini 2015" in the 1961
>     Breviary or in the 1956 Martyrology. Is this a received
>     usage/monastic tradition?

I'm afraid I don't know -- sorry!

With thanks,
Gregor Dick


[1] http://divinumofficium.com/www/horas/Help/credits.html
[2]
https://github.com/DivinumOfficium/divinum-officium/blob/master/web/www/horas/Latin/Tempora/Epi1-0.txt



—Reply to this email directly or view it on GitHub.

**Comment by rarty** [comment]
Well, I think the 1956 Martyrology text (last printed edition) should be used as the base for the "Divinu Afflatu" (mostly as-printed), "Reduced 1955" (remove lesser octaves and vigils to match rubrics) and the "Rubrics 1960" (implement all of *Variationes* to fully match the 1962 Calendar) versions of the office. 

The update in 1960 (See: [Variationes in Mart.](divinum-officium/web/www/horas/Help/Rubrics/Variationes in Martyrologio Romano (AAS 52, 1960).pdf)) is pretty minor (61 total items), but accounts for both 1955 calendar change (~28/61 items) and the 1960 revisions. Each difference is usually only a single deleted line or replaced line.

While I'm sure this has been hashed through before, what exactly is the "cut-off" date for changes in Office for "Divinu Afflatu" and "Reduced 1955"? The Martyrology entries should not contradict what is actually in the calendar for each version. A quick look at the 2014 generated Kalendar on the site shows some inconsistency...

* St Joseph Worker (est. 1955/1956), is not in either.
* Solemnity St Joseph during Easter season, is not in Reduced 1955. (Suppressed in the same decree that added St Joseph the Worker, 1955/56 - so it seems like one or the other should be included)
* St Pius X (est. 1955), is in both.
* Reformed Holy Week (est. 1951/55/56), is in Reduced 1955, but not Divinu Afflatu.
* S. Lawrence of Brindisi (est. 1959), is not in Reduced 1955.

From what I can tell, the 1955 simplifications went into effect Jan. 1, 1956, and the 1960 reform went into effect Jan. 1, 1961.

**Comment by gregordick** [comment]
Each set of rubrics has an associated kalendar that Laszlo selected. For example, 'Trident 1910' uses the kalendar from an 1888 breviary, and 'Divino afflatu' that from 1942. The Martyrology is probably not consistent with any of these. I think LK had one text available and adapted it manually as necessary, but quite possibly not comprehensively.

Support for the 1955 rubrics in particular is incomplete and has many bugs. It's intended to reflect the rubrics and kalendar at the point at which 'Cum nostra' took effect.

This arrangement is not ideal. If you have any opportunities to make things more consistent, please feel free to take them! I'll close this issue now.
