### ISSUE TITLE
Unintentional rank changes?

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3319]
When I integrated changes over the last week today, I saw a lot of rank changes in the output. If these were intentional, you can just close this. If not, there's a bug. Some examples:

- With 1960 rubrics, the vigil of St. Lawrence on 8-9-2022 is a commemoration instead of III class. Only the title changes, not the text presented for the office.
- With Divino afflatu, many Semiduplex are now "Semiduplex II ordinis": 6-17-2022, 6-18-2022
- With 1910 Tridentine rubrics, 12-29-2022 vespers is the Sunday office with a commemoration of St. Thomas Becket instead of a duplex feast of the saint. At terce, I see that it's a semiduplex instead of a duplex.

**Comment by APMarcello3** [comment]
1) August 9 fixed.
2) Days within the octave of Corpus Christi, in DA rubrics, should correctly appear as semiduplex.
3) 12-29 1910 rubrics fixed.

**Comment by FAJ-Munich** [comment]
> With 1910 Tridentine rubrics, 12-29-2022 vespers is the Sunday office with a commemoration of St. Thomas Becket instead of a duplex feast of the saint. At terce, I see that it's a semiduplex instead of a duplex.

... again, that's how it ought to be. Since the 1910 rubrics are implemented using the 1888 Kalendarium, we should not deviate from the official books from back then; i.e., Thomas Becket is Semiduplex feast.
 
![image](https://github.com/DivinumOfficium/divinum-officium/assets/60485740/47e436c0-a22b-4cfb-9dc1-a4d1588d8411)
![image](https://github.com/DivinumOfficium/divinum-officium/assets/60485740/8a9148f2-c07a-44a9-8897-4b033e2d660a)
![image](https://github.com/DivinumOfficium/divinum-officium/assets/60485740/a3a6ef9c-159f-4bc7-a790-93db66471ce8)
![image](https://github.com/DivinumOfficium/divinum-officium/assets/60485740/eaf8c3d1-ceaa-4ee7-955a-6b01283f6f06)

**Comment by fiapps** [comment]
I know very little about Tridentine rubrics, which is why I posed this issue as a question. I defer to your knowledge of them.

**Comment by FAJ-Munich** [comment]
No worries and no offence!
With your first question you have been definately right. I am not very fluent for 1960 and have seen that the Vigil of St Lawrence was wrong for Trid and DA not thinking about the consequence on 1960 by my change. 
On the ranking of the days under DA I have decided to include the additional information on the various ranks of Octaves such that is becomes clearer why some Semiduplex (in particular in the Octave of Corpus Christi) outrank even Duplex II. classis. Previously, these days have been wrongly marked as Feria major and Feria privilegiata which they are not and then they have been changed in the interim to just semiduplex which did not take into account the preferential treatment these octaves have had before the octave massacre of 1955.
