### ISSUE TITLE
Gloria Patri is appearing at the end of psalms and canticles during the Triduum (1960 rubrics)

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3456]
I've been putting off deployment of the recent changes (mainly the new occurrence and concurrence routines) because I found many errors in testing. One is that the Gloria Patri is now appearing at the end of psalms and canticles during the Triduum. Formerly this was correctly showing the rubric "Gloria omittitur".

Example (Good Friday Lauds): https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=3-28-2024&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=

**Comment by APMarcello3** [comment]
Could you kindly enumerate the errors you have found?

**Comment by FAJ-Munich** [comment]
Issues I have discovered myself tonight are:

1. Ordering of Commemorations in the Vernacular:  at the moment the code checks for "Dominica" here and there, failing to recognize the translations like "Sunday", "Sonntag" etc.  (=> in particular in 2nd Vespers on Trinity Sunday)
2. Similar issues may arise where the code checks for "Feria", "Octava", etc. and performs this task on the vernacular instead of the Latin.
3. Commemoration of Octaves on Sunday 2nd Vespers: to avoid double commemorations and to correctly bring the commemoration of 1st Vespers or 2nd Vespers of the Octave (e.g. S. Joseph or Ssmi. Cordis) the routine has to be more flexible to handle two temporas (it is not an issue in the Sanctoral, e.g. Nov 5, 2023.)  (=> I am still uncertain about the best solution, whether to separate the octave from the Sunday or not)

**Comment by fiapps** [comment]
Based on my testing, the issue I reported has been fixed, but perhaps this issue needs to be kept open until the three problems mentioned in FAJ-Munich's comment have also been resolved.

As for reporting the problems I found in testing, I did what I could yesterday. I'll try to report more tomorrow. I normally integrate changes into my fork once a week, and run a large test suite before I deploy the changes. This suite currently contains 1162 cases, and when I run it now, I get 1322 reports of changes. Looking through these to decide what is OK, what is a problem, and then reproducing the problems and reporting them takes time, and the issues I opened yesterday are all I could manage to do that day. I'm fairly sure there are more problems, and I'll report them as I can.
