### ISSUE TITLE
Vespers Sun Jan 7 (Holy Family) DA

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3514]
>Antiphonæ de Laudibus, vel de I Vesperis quoties in eis de hoc Festo facta tantum fuerit commemoratio.

This rubric appears in my 1940 breviary from Pustet and in the Liber Antiphonarius (the Solesmes edition of 1949, reprinted in the 1950s).

DO currently has the antiphons Post Triduum etc. So does the "Restore the ‘54" ordo, and last time that this happened, Rubricarius had this as well, at least based on his blog entry. But the rubric is unambiguous and is present at least for some offices where the antiphons of Lauds are repeated in the evening of the feast itself but a different set is used the day before at I Vespers; the chapter, verse (if different), and Magnificat antiphon are still those of II Vespers, as those of I Vespers were said the previous day.

**Comment by FAJ-Munich** [comment]
Do I understand you correctly that, since 1st Vespers of Holy Family is impeded, it's Antiphons gets transferred to 2nd Vespers; and, moreover this rule applies to other feasts as well: 

In that case, I think the most sensible thing is to implement a variant to the Hymn transferral mechanism where in some years, the transfer tables have a line like `Hy05-18=1`. Maybe this mechanism even exists already as I have never thought about the meaning of entries like `seant01-07=1` in the transfer files before.

**Comment by MRoth1910** [comment]
I **believe** that it applies to other feasts (it should apply to June 24, for example, but I cannot find the rubric).

But yes you do understand what I'm saying. Jan 6 on Saturday = transferred antiphons of the psalms from I Vespers to be said at Vespers of Sunday Jan 7.
