### ISSUE TITLE
The Mass: too much of vertical breakers

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#386]
When the option "Rubrics" is turned off, the Latin text is divided several times immediately after "Preparatio Communionis ". I presume it is caused by the way the recently added rubrics are written (they are the only text in the current line).

It doesn't affect the rubrics later than 1962.

**Comment by mbab** [comment]
``(Iungit manus.)`` and ``(Extendit manus.)`` rubrics are missing from translations.
Adding them fix problem.

**Comment by gregordick** [comment]
@mbab: It seems that you understand the problem.  Could you please prepare a patch?

**Comment by mbab** [comment]
The problem is data line contains only rubrics. When it is ommited it makes empty line and which breaks table cell. In above case translation contains no rubrics in section ``# Preparatio Communionis`` so cell is not broken.

Proposed patch replaces rubrics with ``_`` which are ommited next.

This patch also clean up code a bit.
