### ISSUE TITLE
Comments to the Office?

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#507]
An Italian user proposes to insert the comments to the readings and psalms from the Battisti edition into the Italian translation. I was wondering whether this is feasible or not. Is there a plan to insert commentaries in other languages?

**Comment by ajmalton** [comment]
At the very least let them be optional.But then we must create a new way for them to be optional.AJM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: rl1234567890Sent: Wednesday, April 20, 2016 9:19 PMTo: DivinumOfficium/divinum-officiumReply To: DivinumOfficium/divinum-officiumSubject: [DivinumOfficium/divinum-officium] Comments to the Office? (#507)An Italian user proposes to insert the comments to the readings and psalms from the Battisti edition into the Italian translation. I was wondering whether this is feasible or not. Is there a plan to insert commentaries in other languages?

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by peterdiekertz** [comment]
The German translation I use includes comments, but I have at the moment no plan to add them to the website.
