### ISSUE TITLE
Pius XII Psalter

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#817]
As we have the Pius XII psalter available within the file structure, it makes sense to incorporate it onto the site for those who wish to use it. It seems as though the simplest solution would be to move the unaccented 'psalms' files to the "Obsolete" folder, and simply use the existing $accented syntax to incorporate it with the psalms/psalms1 folders. There could be a selector made available in the Options menu, or on the officium.pl or Pofficium.pl pages, to toggle between the Vulgate and Pius XII psalters. Personally, I am unable to code it in; I would however be grateful if someone would be willing to take on this project.

**Comment by mbab** [comment]
Change psalms should be only in Divino and after?

**Comment by APMarcello3** [comment]
While I will have to look into finding a translation for the Pius XII psalter, I don't see why this should preclude installing this psalter as an option for the Latin.

**Comment by mbab** [comment]
I added `Latin psalms 1942` checkbox in `Options`. Please check 241247eac318b4e078fee18e50a136fe10dbaeae if it is acceptable.

**Comment by APMarcello3** [comment]
Looks fine. Could we please deploy it?

**Comment by APMarcello3** [comment]
Looks good. However, we will have to integrate the Pius XII version of the Invitatory, as well as the Benedictus, Magnificat and Nunc Dimittis.

**Comment by igneus** [comment]
The division of verses now seems to match the traditional division of the Roman Breviary with "Psalterium Gallicanum". But modifications of the verse division is an important feature of "Psalterium Pianum" - the translators took care to restore parallelisms and other features lost in the Septuagint/Vulgate Psalter text or in the way the text was traditionally rendered in the breviary.

Is it OK to adjust verses to match the way they were printed in contemporary breviaries, or is there a reason for the current solution?

**Comment by APMarcello3** [comment]
Please adjust to the printing/orthography as found in breviaries. Thank you.

**Comment by igneus** [comment]
@APMarcello3 Sure. I will resume the work once the semester is over and hopefully finish it this summer.

**Comment by igneus** [comment]
When orthography was mentioned it should be noted that currently the psalms are transcribed from some early edition with the "phonetic orthography" (jam, Jesus, etc.), while since [195x](https://latin.stackexchange.com/questions/5726/church-latin-when-did-the-orthography-change-occur) breviaries and other liturgical books were printed with the "classicizing orthography" (iam, Iesus, etc.). I have one of the newer editions and could also make this orthography update, but I don't find it a good idea, for two reasons: 

1. currently all the other texts use the old orthography, so it makes sense for the psalms to stick to it as well
2. when orthography in all the texts is consistent (old), it is possible to implement an option to render them with orthography updated programmatically (the rules are relatively simple and consistent)
