### ISSUE TITLE
Lectiones Januarii 2018

### ISSUE THREAD

**Issue by BertMostert** [DivinumOfficium/divinum-officium#919]
In this week the lectures of the first nocturn should be read from 1 Cor of St Paul as follows
08-1 the beginning ch 1 vs 1-3,4-9 and 10-13
09-1 ch 05 vs 1-5,6-8 and 9-11
10-1 ch 06 vs 1-6,7-11 and 12-18
11-1 ch 07 vs 1-4,5-9 and 10-14
12-1 ch 13 vs 1-3,4-10 and 11-13
13-1 die octava Epiphaniae ch 16 vs 1-4,5-9,10-14

**Comment by petermottola** [comment]
Although this issue has already been closed, I thought it might be helpful to add this rubric as it appears in my 1963 Collegeville:
1312: "After the 1st Sunday after Epiphany, whatever lessons are left over from the Epistle to the Romans are omitted, and the lessons from the occurring Scripture are taken from the 1st Epistle to the Corinthians, as given below after January 11; and lessons from this epistle are read through the Saturday of that week."
The rubric after January 11, under the heading January 12:
"The lessons from the 1st Epistle to the Corinthians which occur according to the rubric above 1312 are said.  If it is a Saturday, the following lessons [1 Cor 1] are said."

It appears to me that 1 Cor 1 is only read on years where January 12 falls on a Saturday.  Otherwise, the readings of that epistle begin on the Monday after Epiphany with chapter 2.
