### ISSUE TITLE
Choose an office from the Commons

### ISSUE THREAD

**Issue by igneus** [DivinumOfficium/divinum-officium#971]
For purposes of celebrating local feasts (which either don't have proper texts or these are not accessible to the person praying) it should be possible, apart of choosing "hodie", Dedication, officium defunctorum or officium parvum, to choose also one of the Commons and rank of the feast.

**Comment by fiapps** [comment]
There was a similar request in #91, which has now been closed.

**Comment by fiapps** [comment]
At one point I tried to work on this, but I didn't get very far, because understood little about how the code worked.

Instead of using the `votive` parameter, I added a `mycal` parameter that indicated the office to celebrate and its rank, e.g. "Commune/C3.txt 3". Doing it this way would in theory also allow the celebration of a saint whose feast is on a different day in a proper calendar (e.g. "Saints/08-15.txt 3"). However, it's difficult to immagine a reasonable user interface for that, and the calcalc branch should be able to handle custom calendars. It may also be a bad idea as far as security is concerned to let users pass a partial file path.

This is what I tried. It's been a few years, but I think the problem was that it didn't work to celebrate a common directly as an office.

```
sub checkMyCal {
	my ($myCalOffice, $myCalRank) = split(/\s/, strictparam('mycal'));

	# Do nothing if the rank is not a decimal number
	if ($myCalRank !~ /^-?(?:\d+(?:\.\d*)?|\.\d+)$/) {
		warn "$myCalRank numerum non est.";
		return;
	}
	# Do nothing if the specified office does not exist
	if (! -e "$datafolder/Latin/$myCalOffice") {
		warn "Deest officium '$myCalOffice'. mycal = '$mycal'";
		return;
	}

	# Replace office if rank is superior
	if ($rank < $myCalRank) {
		# Filename of the office to celebrate. e.g. Sancti/08-15.txt
		$winner = $myCalOffice;
		# Numeric rank of the office to celebrate:
		# 6 - I class
		# 5 - II class
		# 3 - III class
		$rank = $myCalRank;

		# TODO: set dayname, handle scripture, commemoration

		# fill winner hashes
		%winner = %{officestring($datafolder, $lang1, $winner)};  
    	        %winner2 = %{officestring($datafolder, $lang2, $winner)};
        }
        # else commemorate office if a commemoration is permitted
}
```

**Comment by APMarcello3** [comment]
A further request for an Office/Mass from the Common has arisen for the Rorate Mass during Advent.
